[1단계 - 지하철 노선도 미션] 심바(임선빈) 미션 제출합니다.
woowacourse/javascript-subway pull request #29
Opened 2021-03-23 09:00 UTC by 0imbean0

안녕하세요.
우아한테크코스 3기 심바입니다.

1단계 미션 제출합니다.

### 데모 사이트 - [지하철 노선도](https://bronze-silver-gold-subway.netlify.app/login)

## 🌱 Step1 기능 구현 목록

### 회원가입

- [x] 유저가 회원가입 버튼을 누른다.
- [x] 유저가 이름을 입력한다.
- [x] 유저가 이메일을 입력한다.
- [x] 유저가 비밀번호, 비밀번호 확인을 입력한다.
- [x] 유저가 확인을 누른다.
- [x] JWT(O) -> 첫 페이지 / JWT(X) -> 로그인 페이지

### 로그인

- [x] 유저가 이메일을 입력한다.
- [x] 유저가 비밀번호를 입력한다.
- [x] 유저가 확인을 입력한다.
- [x] 성공 - 로그인 버튼이 로그아웃 버튼으로 바뀐다.
- [x] 실패 - 빨간 글씨

### 로그아웃

- [x] 유저가 로그아웃 버튼을 누른다.
- [x] 성공 - 로그아웃 버튼이 로그인 버튼으로 바뀐다.

2021-03-23 16:53 UTC, ysm0622 requested changes
1단계 고생하셨습니다! 👏 👏 👏 👏

2021-03-23 16:53 UTC, ysm0622 commented on src/css/ui/modules/form.css
> +  box-shadow: 4px 4px 10px 0px rgb(78 207 224 / 32%), 0 0 0 35px white inset !important;
여기에 !important가 필요한 이유는 무엇인가요?
!important는 특수한 상황이 아니라면 사용을 지양하는것이 좋기 때문에
반드시 사용해야만 하는 이유가있다면 코드리뷰에 참고할 수 있도록 코멘트를 달아주시면 좋을것같아요! 👍

2021-03-23 16:53 UTC, ysm0622 commented on src/js/components/login/index.js
> +    }
실제 statusCode가 이렇게 내려오나요?
일반적으로 HTTP 5XX 에러는 서버 내부에러를 뜻하는데 여기선 그렇지 않은것같네요! 👀

2021-03-23 16:53 UTC, ysm0622 commented on src/js/components/signup/index.js
> +            await this.validateEmail(target.value);
이벤트리스너 함수 하나가 너무 큰것같아요! 중복되는 로직이나 작은 단위로 분리할수있을까요?

2021-03-23 16:53 UTC, ysm0622 commented on src/js/stateManagers/AccessTokenManager.js
> +  }
AccessTokenManager가 메뉴 렌더링을 위해 굳이 subscribe, notify 같은 옵저버패턴의 함수들를 가져야할까요?
AccessTokenManager는 뭔가 토큰만 매니징해주면 되는 객체같은데 너무 다양한 일을 한다고 생각되어요. 👀 
(옵저버패턴을 사용하기위해 만든느낌이랄까..?)

2021-03-23 16:53 UTC, ysm0622 commented on src/js/utils/fetch.js
> +};
자주 사용되는 headers나 body의 JSON.stringify 같은 반복되는 것들도 추상화 할 수 있지않을까요?
많이 사용되는 오픈소스 라이브러리인 axios 같은 오픈소스에서는 어떻게 추상화하고있는지 살펴보는것도 도움이 될것같아요 👍

2021-03-23 16:53 UTC, ysm0622 commented on src/js/components/line/template/main.js
> +          </div>
이렇게 div를 한 depth 더 감싸주어야 하는 이유는 무엇인가요? 👀

2021-03-24 11:48 UTC, 0imbean0 commented on src/css/ui/modules/form.css
> +  box-shadow: 4px 4px 10px 0px rgb(78 207 224 / 32%), 0 0 0 35px white inset !important;
자동 완성 된 input(email, password)에 대해서 기본 적용된 스타일이 마음에 들지 않아 임의로 CSS를 만들어서 적용했습니다. 
Github 로그인 폼에서도 같은 방법으로 구현되어 있어서 사용해보았습니다. 좋지 않은 문법인가요?

2021-03-24 11:54 UTC, 0imbean0 commented on src/js/components/login/index.js
> +    }
HTTP 5XX 에러는 서버 내부에러라는 걸 인지하였지만, 현재 API 문서에는 등록되지 않은 이메일에 대한 처리가 되지않아 임의로 처리하였습니다. 그래서 API가 추가되면 수정하려 하였는데, 현재의 사용성을 높이려고 부적절한 처리를 한 것 같습니다. 수정하겠습니다. 😔😢

2021-03-24 12:04 UTC, 0imbean0 commented on src/js/stateManagers/AccessTokenManager.js
> +  }
AccessTokenManager에서 Observer Pattern을 사용하는 이유는 App의 하위 컴포넌트에서 App에 있는 renderHeader라는 함수를 사용하기 위해서 입니다. 

Token의 유무는 로그인의 상태와 같은데, 로그인의 상태에 따라 그려주는 Header가 달라집니다.

그래서 Token의 유무(State)를 감지해서 Header를 바꾸어 주는 것이 renderHeader 함수를 모든 컴포넌트에서 호출하는 것보다 코드의 중복을 줄일 수 있어 효율적이라고 생각했습니다.

2021-03-24 12:45 UTC, 0imbean0 commented on src/js/components/line/template/main.js
> +          </div>
이번 단계에서는 아직 모달을 사용하지 않아서 주어진 템플릿 코드를 확인하지 못하였습니다.

다음 단계에서 모달을 사용할 때, 확인하고 수정하겠습니다. 😥

2021-03-24 12:45 UTC, 0imbean0 commented on src/js/components/signup/index.js
> +            await this.validateEmail(target.value);
관련 코드를 수정 하였습니다. 😀

2021-03-25 03:32 UTC, 0imbean0 commented on src/js/utils/fetch.js
> +};
관련 코드를 수정 하였습니다. 
코드가 더욱 간결해 진 것 같습니다.😀

2021-03-27 05:54 UTC, ysm0622 commented on src/css/ui/modules/form.css
> +  box-shadow: 4px 4px 10px 0px rgb(78 207 224 / 32%), 0 0 0 35px white inset !important;
네 특수한 상황에서만 사용되는 최후의 수단이라고생각하시고,
꼭 필요한 상황이 온다면 주석이나 코드리뷰 코멘트를 달아주시는게 좋을것같아요.

2021-03-27 05:56 UTC, ysm0622 approved these changes
고생하셨습니다! :)

다음단계에서 봬요! 👏 👏 👏

2021-03-27 05:56 UTC, merged