[2단계-지하철 노선도 미션] 디토(천영석) 제출합니다.
woowacourse/javascript-subway pull request #48
Opened 2021-04-01 10:05 UTC by dudtjr913

## [데모 페이지](https://ditto-subway-step2.netlify.app/)

안녕하세요. Jbee 리뷰어님!! 2단계 미션 제출합니다.

## 도전한 것
- `station, line, section`은 서로 연관이 되어 있다고 생각했고, 3개의 데이터를 한 번에 관리하기 위해 `싱글톤 패턴`을 사용해 데이터를 관리하는 모델을 만들었습니다.  
- `station, line, section`의 데이터를 변경하지 않고 라우팅을 시도했을 때, api를 요청하고, 템플릿을 만드는 것이 불필요한 작업이라고 생각했습니다. 그래서 캐시 방식을 사용하여 `station, line, section`의 데이터가 변경되지 않으면 템플릿도 새롭게 생성하지 않고, api 요청도 보내지 않도록 구현했습니다. 

## 🎯🎯 step2

### 지하철역 관리 기능

- [x] 지하철역을 등록할 수 있다.
  - [x] 지하철역은 2글자 이상이어야 한다.
  - [x] 엔터키 또는 마우스 클릭으로 역을 추가할 수 있어야 한다.
  - [x] 지하철역의 이름은 최대 20자 이하이다.
  - [x] 중복된 지하철역은 추가할 수 없다.
- [x] 지하철역의 이름을 수정할 수 있다.
  - [x] 수정하는 UI는 modal을 이용하여 수정할 수 있게 한다.
- [x] 지하철역을 삭제할 수 있다.
  - [x] 삭제 시 confirm을 이용하여 한 번 더 유저가 확인할 수 있어야 한다.
  - [x] 이미 노선에 등록된 역인 경우 삭제할 수 없다.

### 지하철 노선 관리 기능

- [x] 지하철 노선을 등록할 수 있다.
  - [x] 지하철 노선의 이름은 2글자 이상이어야 한다.
  - [x] 중복된 지하철 노선 이름이 등록될 수 없다.
  - [x] 지하철 노선의 이름은 최대 10자 이하이다.
  - [x] 지하철 노선 생성시 필요한 값은 색상, 상행역, 하행역, (최초 상행역과 하행역 구간의)거리, 시간이다.
- [x] 지하철 노선을 수정할 수 있다.
  - [x] 지하철 노선의 이름, 색상을 수정할 수 있다.
- [x] 지하철 노선을 삭제할 수 있다.
  - [x] 삭제 시 confirm을 이용하여 한 번 더 유저가 확인할 수 있어야 한다.

### 지하철 구간 관리 기능

- [x] 지하철 노선에 구간을 추가, 삭제할 수 있다.
- [x] 구간 조회 시, 노선을 변경하면 해당 노선의 Color로 Select 엘리먼트의 배경색을 변경한다.

## 디렉토리 구조
📦js
 ┣ 📂api
 ┃ ┗ 📜httpClient.js
 ┣ 📂components
 ┃ ┣ 📜App.js
 ┃ ┣ 📜Lines.js
 ┃ ┣ 📜Sections.js
 ┃ ┣ 📜SignIn.js
 ┃ ┣ 📜SignUp.js
 ┃ ┗ 📜Stations.js
 ┣ 📂inputChecker
 ┃ ┗ 📜inputChecker.js
 ┣ 📂model
 ┃ ┗ 📜UserDataManager.js
 ┣ 📂requestData
 ┃ ┗ 📜requestUserData.js
 ┣ 📂router
 ┃ ┗ 📜Router.js
 ┣ 📂templates
 ┃ ┣ 📜lines.js
 ┃ ┣ 📜main.js
 ┃ ┣ 📜sections.js
 ┃ ┣ 📜signIn.js
 ┃ ┣ 📜signUp.js
 ┃ ┗ 📜stations.js
 ┣ 📂token
 ┃ ┗ 📜Token.js
 ┣ 📂utils
 ┃ ┣ 📜calculate.js
 ┃ ┣ 📜constants.js
 ┃ ┣ 📜cookie.js
 ┃ ┣ 📜debounce.js
 ┃ ┣ 📜deepFreeze.js
 ┃ ┣ 📜dom.js
 ┃ ┣ 📜mock.js
 ┃ ┣ 📜modal.js
 ┃ ┗ 📜snackbar.js
 ┣ 📂validators
 ┃ ┣ 📜boolean.js
 ┃ ┗ 📜validation.js
 ┗ 📜index.js

리뷰해주셔서 감사합니다.😍😍👍👍

2021-04-03 12:22 UTC, JaeYeopHan requested changes
수고하셨습니다! 👏 👏 👏 
코멘트 몇개 남겼어요~

1. 초기에 렌더링 될 때, CSS가 로드되지 않는 시점이 잠깐 있어서 깜빡이지 않던가요? 시간이 되시면 이 문제가 왜 발생했는지 알아보고 수정해보셔도 좋을 것 같아요!
2. `components` 디렉토리가 컴포넌트라기 보단 한 페이지에 대한 모든 역할을 수행하고 있는 것 같은데, 조금 더 작은 단위의 컴포넌트들로 나눠봐도 좋을 것 같아요~

2021-04-03 12:22 UTC, JaeYeopHan commented on src/js/components/App.js
> +    this.map = new Map({ initializeRoutedPage: this.initializeRoutedPage.bind(this) });
자료구조랑 헷갈리겠는데요?ㅋㅋ 😅

2021-04-03 12:22 UTC, JaeYeopHan commented on src/js/components/Lines.js
> +      alert(error.message);
이런 단순 alert가 반복되는 것 같은데 이런 에러 처리는 전역에서 처리해주면 어떨까요?

2021-04-03 12:22 UTC, JaeYeopHan commented on src/js/validators/boolean.js
> +  return $target.classList.contains('modal') && $target.classList.contains('open');
`'modal'`도 classname일 것 같아요! 다른 class들은 상수로 관리되고 있는데, 얘만 아닌 이유가 따로 있을까요??

2021-04-03 12:22 UTC, JaeYeopHan commented on src/js/requestData/requestUserData.js
> +};
1. try-catch
2. response.ok 분기
3. 반환 시 .json()

요것들까지 httpClient가 해줄 수는 없을까요? (엄청 반복되고 있어서요!)

2021-04-03 12:22 UTC, JaeYeopHan commented on src/js/requestData/requestUserData.js
> +  }
바로 throw 해주는데, catch는 왜 해주는 걸까요?

2021-04-03 12:41 UTC, dudtjr913 commented on src/js/components/App.js
> +    this.map = new Map({ initializeRoutedPage: this.initializeRoutedPage.bind(this) });
저도 방금 제 코드를 보고 헷갈렸네요..ㅋㅋ 네이밍 변경하도록 하겠습니다.

2021-04-03 12:43 UTC, dudtjr913 commented on src/js/validators/boolean.js
> +  return $target.classList.contains('modal') && $target.classList.contains('open');
아.. 수정하도록 하겠습니다.ㅠ.ㅠ

2021-04-06 14:15 UTC, dudtjr913 commented on src/js/requestData/requestUserData.js
> +  }
async await이 사용되는 함수에서는 항상 try-catch를 사용해서 에러 처리를 해야되는지 알았습니다.
그래서 어쩔 수 없이 위와 같은 형태를 사용하게 되었습니다. 

조금 더 자세하게는 `requestAddStation()` 함수를 사용하는 쪽에서도 async await을 사용해야 했기에 try-catch를 사용해야 한다고 생각했었고,
`requestAddStation()`함수의 catch에서 throw를 하지 않으면 이 함수를 사용하는 쪽에서 catch에 담기지 않기 때문에 이렇게 사용하게 되었습니다.
```javascript
    try {
      const stationData = await requestAddStation({ name: stationName });
      this.userDataManager.setStationData(stationData);
    } catch (error) {
      alert(error.message);
    }
```

하지만 에러는 호출자 방향으로 전파가 되기 때문에 async await을 사용하는 모든 함수에서 try-catch로 에처러리를 할 필요가 없다는 것을 알게 되었습니다. 그래서 현재는 throw가 되면 catch에서는 alert을 하도록 구현을 했습니다.

2021-04-06 19:19 UTC, dudtjr913 commented on src/js/requestData/requestUserData.js
> +};
해당 커밋입니다! 
801baf1
httpClient에서 1, 2, 3 모두 할 수 있도록 구현했습니다.

2021-04-06 19:22 UTC, dudtjr913 commented on src/js/components/Lines.js
> +      alert(error.message);
801baf1
httpClient에서 alert를 할 수 있도록 구현했습니다.

2021-04-06 19:22 UTC, dudtjr913 commented on src/js/components/App.js
> +    this.map = new Map({ initializeRoutedPage: this.initializeRoutedPage.bind(this) });
SubwayMap으로 변경하였습니다!

2021-04-06 19:24 UTC, dudtjr913 commented on src/js/validators/boolean.js
> +  return $target.classList.contains('modal') && $target.classList.contains('open');
해당 커밋입니다. c56c941 
수정했습니다!

2021-04-06 19:48 UTC, dudtjr913 commented
코드 리뷰 감사합니다.
피드백 모두 반영했습니다!

> 초기에 렌더링 될 때, CSS가 로드되지 않는 시점이 잠깐 있어서 깜빡이지 않던가요? 시간이 되시면 이 문제가 왜 발생했는지 알아보고 수정해보셔도 좋을 것 같아요!

style-loader를 대신하여 MiniCssExtractPlugin을 통해 해결했습니다. 
하지만 정확한 이유를 찾지 못했습니다... 
style-loader는 로드하는 데 시간이 오래 걸려서 깜빡이는 현상이 나타나는 것인가요? (멍청한 질문 죄송합니다...)

> components 디렉토리가 컴포넌트라기 보단 한 페이지에 대한 모든 역할을 수행하고 있는 것 같은데, 조금 더 작은 단위의 컴포넌트들로 나눠봐도 좋을 것 같아요~

컴포넌트 분리 했습니다! 잘못된 부분 있으면 알려주세요😍😍

2021-04-08 01:59 UTC, JaeYeopHan commented on src/js/requestData/requestUserData.js
> +  }
👏 👏 👏 👏 👏 👏 👏 👏

2021-04-08 02:05 UTC, JaeYeopHan approved these changes
> style-loader를 대신하여 MiniCssExtractPlugin을 통해 해결했습니다.
하지만 정확한 이유를 찾지 못했습니다...
style-loader는 로드하는 데 시간이 오래 걸려서 깜빡이는 현상이 나타나는 것인가요? (멍청한 질문 죄송합니다...)

디토님이 만든 앱을 브라우저가 어떻게 그리는지(?) 알아보면 많은 도움 될 것 같습니다!
문서도 하나 추천드려요!

Critical rendering path 관련 (https://developers.google.com/web/fundamentals/performance/critical-rendering-path?hl=ko) 글 중
rendering blocking
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css?hl=ko

추천해봅니다!

2021-04-08 02:06 UTC, merged

2021-04-17 11:02 UTC, dudtjr913 commented
## 학습로그
## [모듈 번들러] (웹팩) - 5
### 내용
- 가독성과 편의를 위해 모듈화하여 작성된 파일들을 하나의 파일로 번들링해주기 위해 나타난 것이 웹팩이다.
- 모듈화된 파일들을 브라우저에서 로딩을 하게 되면 그만큼 네트워크 비용이 발생하기 때문이 비효율적이다.
- 그래서 웹팩에서는 자바스크립트, 스타일 시트, 이미지 등 모든 것들을 번들로 묶은 자바스크립트로 만들어준다.

### 링크
- [웹팩 공식 문서](https://webpack.js.org/)
- [웹팩이란?](https://joshua1988.github.io/webpack-guide/webpack/what-is-webpack.html#%EB%AA%A8%EB%93%88%EC%9D%B4%EB%9E%80)

## [트랜스파일러] (babel) - 5
### 내용
- 바벨은 최신 문법으로 작성된 자바스크립트 코드를 과거의 브라우저에서도 호환될 수 있도록 변환해주는 도구이다.
- 바벨 자체가 변환해준다기보다는 바벨 플러그인이 모여 코드를 변환해준다고 생각하면 된다.
- 각종 유용한 플러그인들의 집합은 프리셋이라고 한다.
- 폴리필을 사용하여 ES5에 존재하지 않는 Promise, Map, Set과 같은 코드를 동작할 수 있도록 할 수 있다.
### 링크
- [바벨 공식 문서](https://babeljs.io/)
- [바벨이란 무엇인가?](https://devowen.com/293)


## [추상화] (httpClient) - 7
### 내용
- fetch 요청이 중복되는 것을 추상화하여 코드의 가독성을 증가시킴
### 링크
- [httpClient 파일](https://github.com/dudtjr913/javascript-subway/blob/2c33177297c1f0398b878d2c724de0f31a2d15ca/src/js/api/httpClient.js)

## [에러 핸들링] (try-catch) - 7
### 내용
- try-catch는 에러가 발생했을 때, 스크립트가 다운되는 것을 방지하고, 에러를 잡아서 원하는 대로 동작하게 할 수 있다.
- 에러는 호출자 방향으로 전파된다. 
- throw 연산자를 사용해서 에러를 직접 만들어서 던질 수 있다.
- throw에는 원시형 자료를 포함한 모든 것이 사용될 수 있는데, 내장 에러와의 호환성을 위해 name과 message 프로퍼티를 가지고 있는 것을 권장한다. 가장 많이 쓰이는 방법은 new Error() 객체를 사용하는 것이다.

### 링크
- [모던 자바스크립트 try-catch](https://ko.javascript.info/try-catch)

## [디자인 패턴] (컴포넌트) - 7
### 내용
- 컴포넌트 패턴은 기능의 부품화라고 보면 된다.
- 기능을 부품화하게 되면 코드의 종속성을 끊어주고, 유연하게 되며 재사용성이 높아진다.
- Has-A관계라고 생각하면 쉽다. 지하철앱은 노선 관리 기능을 가지고 있다. -> 노선 관리 기능 컴포넌트로 분리

### 링크
- [컴포넌트 패턴 질문](https://www.inflearn.com/questions/32918)