[2,3단계 - 지하철 노선도 미션] 미키(권세진) 미션 제출합니다.
woowacourse/javascript-subway pull request #55
Opened 2021-04-02 06:29 UTC by 0307kwon

## 1단계 - 지하철 노선도 미션 🚋

[데모페이지](https://0307kwon.github.io/javascript-subway/)

안녕하세요 @ysm0622 님! @jum0 와 페어 중인 미키입니다! 🐭
미완성인 코드를 내려니 마음이 아프네요....ㅠㅠ
2단계 기능과 코드 구조는 완성했고
`리팩터링(TODO 부분)과 TEST 부분, 그리고 3단계 기능이 미완성`인 채로 있습니다.
최대한 빨리 추가적으로 커밋 보내도록 하겠습니다! 

<img src="https://user-images.githubusercontent.com/48755175/113385099-660d0580-93c2-11eb-83fd-976baff1be40.png"  width="600px" />

## 📁 클래스 상속 구조
```
Component
    |`--- HomeComponent
    |`--- LoginComponent
    |`--- SignupComponent
    |`--- MyInfoComponent
    |`--- StationComponent
    |`--- LineComponent
    |`--- SectionComponent
    |
    Page
    `--- AppPage

  Modal
    |`--- StationModal ---StationRevisionComponent
    |`--- LineModal --- LineCreationComponent, LineRevisionComponent
    |`--- SectionModal --- SectionCreationComponent
    
```

## ✨ 미키 & 주모 컨벤션

- prefix 컨벤션
  - '\_' : protected
  - 'handle' : state의 값이 변경되었을 때 호출되는 콜백
  - 'on' : element의 이벤트에 의해 호출되는 콜백

2021-04-04 12:58 UTC, ysm0622 requested changes
고생하셨습니다! 👏 👏 👏 👏 👏

2021-04-04 12:58 UTC, ysm0622 commented on src/js/Pages/AppPage.js
> +    const isLogout = accessToken === KEYWORD.LOGOUT;
토큰이랑 'logout' 문자열을 비교하는 이유는 무엇인가요?
token이 있고, 없을때 isAuthenticated 라는 값을 true/false로 조정해주는게 적절할것같은데요! 👀

2021-04-04 12:58 UTC, ysm0622 commented on src/js/Pages/AppPage.js
> +    this.accessTokenState.Data = KEYWORD.LOGOUT;
토큰은 어디에 저장하는게 적절할까요?
Class property에 저장해도 괜찮을까요?

2021-04-04 12:58 UTC, ysm0622 commented on src/js/Pages/Page.js
>      }
뭔가 early return을 해야할것같은 구조인데요? 👀

2021-04-04 12:58 UTC, ysm0622 commented on src/js/State.js
> +  set Data(value) {
Data 앞글자가 대문자인 이유가 궁금해요 👀

2021-04-04 12:58 UTC, ysm0622 commented on src/js/State.js
> +    if (JSON.stringify(this.#state) === JSON.stringify(value)) return;
JSON.stringify 로 직렬화하는 작업은 생각보다 비용이 클수도 있는 동기 작업인데요.
상태를 Data를 set 할때마다 state나 value 객체가 엄청 크다면 성능저하가 일어날 수도 있는 코드 같아요 !

2021-04-04 12:58 UTC, ysm0622 commented on src/js/State.js
> +    this.Data = myData;
this.Data array에 직접 push하지 않고 myData라는 변수를 만든 이유가 무엇인가요?
immutablility를 의도한것같은데, 이렇게하면 진짜 immutable 할까요?

2021-04-04 12:58 UTC, ysm0622 commented on src/js/components/FullMapComponent.js
> +      console.log(lines);
👀

2021-04-04 12:58 UTC, ysm0622 commented on src/js/components/FullMapComponent.js
> +      $(`#${ID_SELECTOR.FULL_MAP_LINE_LIST}`).innerHTML = linesTemplate;
함수 하나가 API요청과 화면에 View를 그리는 작업을 모두 하고있는 것같은데요.
분리할 수 있을까요?

2021-04-04 12:58 UTC, ysm0622 commented on src/js/components/LoginComponent.js
> +      console.error('accessToken이 존재하지 않습니다.');
이 에러는 개발자가 봐야하는 에러일까요? 유저가 봐야하는 에러일까요?
accessToken이 없다는 뜻은 로그인하지 않아서 권한이 없다는 뜻이랑 같을 것 같은데
유저에게 적절한 메시지를 보여주는것이 더 좋지 않을까요?

2021-04-04 12:58 UTC, ysm0622 commented on src/js/utils/fetch.js
> +};
fetch할때마다 매번 accessToken을 파라미터로 넘겨야할까요?
fetch 함수를 좀더 범용적으로 wrapping하면 매번 토큰을 넘기지않고,
매번 body: JSON.stringify하지 않고, 매번 headers: Authorization 헤더를 넣어주지 않고 API요청하는 코드의 중복을 추상화 할 수 있을 것같은데요! 👀

2021-04-04 12:58 UTC, ysm0622 commented on src/js/components/StationComponent.js
> +      return;
return문이 꼭 필요한가요?

2021-04-08 08:44 UTC, 0307kwon commented on src/js/Pages/AppPage.js
> +    this.accessTokenState.Data = KEYWORD.LOGOUT;
class property는 새로고침 할 때마다 정보가 날아가는 휘발성이기 때문에
새로고침 할 때마다 매번 로그인을 다시해야하는 사용자 입장에서 불편하다는 것을 알게 되었습니다!

그리고 cookie vs localStorage 중 어느 곳에 저장해야할 것인가에 대해 고민이 되었는데
인터넷을 찾아보니 굉장히 의견이 분분하더군요!
그래서 제가 스스로 XSS와 CSRF 측면에서 생각해 보았을 때
1. XSS는 뚫리면 끝이기 때문에 어차피 막아야함 
2. httpOnly 쿠키로 인증하려면 백엔드 서버와의 조율이 필요함

등의 이유로 XSS는 취약하지만 CSRF에는 강한 **localStorage**를 사용하기로 결정하였습니다!
혹시 제가 잘못 알고 있는 부분이나 추가로 알면 좋은 점들이 있을까요?!
[벨로그](https://velog.io/@0307kwon/JWT%EB%8A%94-%EC%96%B4%EB%94%94%EC%97%90-%EC%A0%80%EC%9E%A5%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C-localStorage-vs-cookie)에도 자세히 정리해보았습니다! 가감없는 피드백 부탁드려요! ㅎㅎ 😁

2021-04-08 12:59 UTC, 0307kwon reviewed
꼼꼼한 피드백 감사합니다 @ysm0622 님!

# 🙋‍♂️ 질문이 있습니다!
[개발자가 봐야하는 에러일까요? 유저가 봐야하는 에러일까요?](https://github.com/woowacourse/javascript-subway/pull/55#discussion_r606797376)
[immutablility를 의도한것같은데, 이렇게하면 진짜 immutable 할까요?](https://github.com/woowacourse/javascript-subway/pull/55#discussion_r606796925)
[JSON.stringify 로 직렬화하는 작업은 생각보다 비용이 클수도 있는 동기 작업](https://github.com/woowacourse/javascript-subway/pull/55#discussion_r609612601)
[토큰은 어디에 저장하는게 적절할까요?](https://github.com/woowacourse/javascript-subway/pull/55#discussion_r609477310)

## JWT는 쿠키나 localStorage에 저장하기 - 5

### 링크
https://velog.io/@0307kwon/JWT%EB%8A%94-%EC%96%B4%EB%94%94%EC%97%90-%EC%A0%80%EC%9E%A5%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C-localStorage-vs-cookie

## immutability - 3
immutability를 은연 중에 알고 있었지만 확실한 용어는 처음 알게되었네요
Object의 assign과 freeze 메서드도 불변성을 위해 사용하는 것이었군요! 

### 링크
https://poiemaweb.com/js-immutability

## JSON의 직렬화는 생각보다 비용이 큰 작업이다. - 2
꼭 필요한 곳에만 쓰겠습니다!

2021-04-08 12:59 UTC, 0307kwon commented on src/js/Pages/AppPage.js
> +    const isLogout = accessToken === KEYWORD.LOGOUT;
원래 옵저버 패턴으로 accessToken의 변화를 감지하고 로그인/로그아웃 상태를 판별하기 위해 이 코드가 필요했습니다.
이 코드를 작성하면서도 `isAuthenticated 같은 state를 만들어주는게 낫지 않을까?` 하는 생각이 들었습니다.
그런데 옵저버 패턴을 제거하고 localStorage에서 accessToken을 관리하게되니
KEYWORD.LOGOUT으로 판별해줄 필요가 없게 되었습니다.
그래서 일단은 이 부분을 지우고
```
const accessToken = localStorage.getItem(LOCAL_STORAGE_KEY.ACCESS_TOKEN);

if (!accessToken) {
      this.logout();
      return;
    }

 this.login();
```
이런 방식으로 바꾸었습니다! 괜찮은 방식이 될 수 있을까요?!

2021-04-08 12:59 UTC, 0307kwon commented on src/js/Pages/AppPage.js
> +    this.accessTokenState.Data = KEYWORD.LOGOUT;
class property는 새로고침 할 때마다 정보가 날아가는 휘발성이기 때문에
새로고침 할 때마다 매번 로그인을 다시해야하는 사용자 입장에서 불편하다는 것을 알게 되었습니다!

그리고 cookie vs localStorage 중 어느 곳에 저장해야할 것인가에 대해 고민이 되었는데
인터넷을 찾아보니 굉장히 의견이 분분하더군요!
그래서 제가 스스로 XSS와 CSRF 측면에서 생각해 보았을 때
1. XSS는 뚫리면 끝이기 때문에 어차피 막아야함 
2. httpOnly 쿠키로 인증하려면 백엔드 서버와의 조율이 필요함

등의 이유로 XSS는 취약하지만 CSRF에는 강한 **localStorage**를 사용하기로 결정하였습니다!
혹시 제가 잘못 알고 있는 부분이나 추가로 알면 좋은 점들이 있을까요?!

**[벨로그](https://velog.io/@0307kwon/JWT%EB%8A%94-%EC%96%B4%EB%94%94%EC%97%90-%EC%A0%80%EC%9E%A5%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C-localStorage-vs-cookie)에도 자세히 정리해보았습니다! 가감없는 피드백 부탁드려요!** ㅎㅎ 😁

2021-04-08 12:59 UTC, 0307kwon commented on src/js/Pages/Page.js
>      }
앗 미쳐 보지못했네요! 감사합니다 😁

2021-04-08 12:59 UTC, 0307kwon commented on src/js/State.js
> +  set Data(value) {
setter와 getter는 직접 해당 인스턴스 속성에 접근한다는 느낌이 들어
오해를 줄 수 있을 것 같아 대문자로 작성하였습니다!

get Data는 실제 데이터의 참조값이 아닌 복사한 값을 가져온다는 느낌을 주고
set Data는 속성 값에 바로 대입하는 것이 아닌 입력값을 검증하여 대입한다는 느낌을 주고 싶었습니다.
혹시 잘못된 방법일까요?! 😊

2021-04-08 12:59 UTC, 0307kwon commented on src/js/components/FullMapComponent.js
> +      console.log(lines);
헉! 😢 console.log가 왜... ㅠㅠ 수정했습니다!

2021-04-08 12:59 UTC, 0307kwon commented on src/js/components/FullMapComponent.js
> +      $(`#${ID_SELECTOR.FULL_MAP_LINE_LIST}`).innerHTML = linesTemplate;
원래 load를 `api 요청 + view에 렌더` 의 의미로 사용하고 있었습니다.
그런데 지금 보니 굳이 두가지 일을 동시에 하는 함수로 만들 필요가 있었을까 라는 생각이 드네요!
피드백 감사합니다! 😁

2021-04-08 12:59 UTC, 0307kwon commented on src/js/components/LoginComponent.js
> +      console.error('accessToken이 존재하지 않습니다.');
이 부분에서 저희 의도는 개발자가 props로 accessTokenState를 넘겨주지 않았을 때
오류를 발생시키려고 하였습니다! 이런 의도라면 개발자를 위한 에러가 아닐까요?! 궁금합니다 🙋‍♂️

우선은 accessToken의 관리가 localStorage로 바뀌게 되면서 필요가 없는 코드인 것 같아
삭제했습니다 😊

2021-04-08 12:59 UTC, 0307kwon commented on src/js/components/StationComponent.js
> +      return;
헉 필요가 없네요! 삭제하였습니다! 😊

2021-04-08 12:59 UTC, 0307kwon commented on src/js/State.js
> +    this.Data = myData;
현재 this.Data는 State 클래스의 get Data()를 부르고 있습니다!
그리고 get Data()는 아래와 같습니다.
```
get Data() {
    return this.#deepCopy(this.#state);
}
```
deepCopy는 JSON.Stringify와 JSON.parse를 이용해서 깊은 복사를 하고 있습니다.
복사 후 setter를 이용해서 대입하는 형식은 immutable하다고 생각하고 있습니다. 
(freeze를 쓰지 않아 허술하긴 합니다 ㅜㅠ 😢)
혹시 제가 잘못 알고 있는 부분이 있을까요? 🙋‍♂️

(JSON으로 deepCopy하는 부분은 성능 개선을 위해 현재는 JSON을 사용하지 않고 다시 만든 상태입니다!)

2021-04-08 12:59 UTC, 0307kwon commented on src/js/State.js
> +    if (JSON.stringify(this.#state) === JSON.stringify(value)) return;
다른 곳으로 데이터를 전송하는 것이 아닌데 굳이 직렬화 하는 작업은 비용이 큰 작업이군요!
JSON 없이 코드를 작성해봤습니다! 이런 방식으로 하면 비용을 조금 줄일 수 있을까요?
```
#deepValidateEquality = (target, source) => {
  const targetKeys = Object.keys(target);
  const sourceKeys = Object.keys(source);

  if (targetKeys.length !== sourceKeys.length) {
    return false;
  }

  return targetKeys.every(key => {
    if (source[key] === undefined) {
      return false;
    }

    if (typeof target[key] === 'object') {
      return this.#deepValidateEquality(target[key], source[key]);
    }

    return target[key] === source[key];
  });
};
```

2021-04-08 12:59 UTC, 0307kwon commented on src/js/utils/fetch.js
> +};
확실히 번거로움이 줄었네요! 감사합니다! 😁

2021-04-08 13:02 UTC, ysm0622 commented on src/js/Pages/AppPage.js
> +    const isLogout = accessToken === KEYWORD.LOGOUT;
네 좋습니다! 👍

2021-04-08 13:06 UTC, ysm0622 commented on src/js/State.js
> +  set Data(value) {
잘못된 방법은 아닙니다! 그렇게 작성한 이유와 근거가 충분히 납득할만하다는게 중요한것같아요! 👍 
그런 부분에 있어서, 과연 앞글자를 대문자로 작성하는 것만으로 위에 작성하신 것과 같은 "느낌"을 줄 수 있나? 생각해보시면 좋을것같아요.

2021-04-08 14:01 UTC, ysm0622 commented on src/js/State.js
> +    if (JSON.stringify(this.#state) === JSON.stringify(value)) return;
음.. 그래도 결국 객체 전체를 재귀로 순회한다는 점에서 큰 성능차이는 없을것같은데,
코드를 변경할 필요는 없을 것 같고 이러한 형태는 나중에 성능저하를 일으킬수 있는 코드라고 인지하고계시면 좋을것같아요 👍

2021-04-08 14:03 UTC, ysm0622 commented on src/js/State.js
> +    this.Data = myData;
`this.Data = this.Data.push(value)` 와 다를까요? 👀

2021-04-08 14:04 UTC, ysm0622 commented on src/js/components/LoginComponent.js
> +      console.error('accessToken이 존재하지 않습니다.');
그러한 의도라면 좋습니다 👍

2021-04-08 14:10 UTC, ysm0622 commented on src/js/Pages/AppPage.js
> +    this.accessTokenState.Data = KEYWORD.LOGOUT;
저는 cookie에 저장하는 편입니다. (가능하다면 httpOnly)
쿠키는 별도로 헤더에 담지 않아도 요청을 보낼때 자동으로 담아서 보내지기 때문에 
매번 서버로의 요청에 담아야하는 토큰이라는 성격과 잘 맞고, 코드도 더 간결하게 작성할 수 있게 되는것같아요 👍

2021-04-11 04:53 UTC, 0307kwon commented
리뷰어님 테스트 코드와 코드 수정 마쳤습니다! 😁

2021-04-11 15:19 UTC, ysm0622 approved these changes
고생많으셨습니다! 👍

2021-04-11 15:19 UTC, merged