[2,3단계 - 지하철 노선도 미션] 곤이(김기융) 미션 제출합니다.
woowacourse/javascript-subway pull request #61
Opened 2021-04-02 13:44 UTC by yungo1846

안녕하세요 리뷰어님!
이번 미션은 2단계와 3단계를 동시에 제출하게 됐습니다 😊
레벨 1 기간 동안 항상 좋은 피드백 남겨주셔서 덕분에 많이 배울 수 있었습니다.
감사합니다!!!

## 🎯🎯 step2

### 지하철역 관리 기능

- [x] 지하철역을 등록할 수 있다.
  - [x] 엔터키 또는 마우스 클릭으로 역을 추가할 수 있어야 한다.
  - [x] 중복된 지하철역은 추가할 수 없다.
  - [x] 지하철역은 2글자 이상, 20자 이하여야 한다.
- [x] 지하철역의 이름을 수정할 수 있다.
  - [x] 수정하는 UI는 modal을 이용하여 수정할 수 있게 한다.
- [x] 지하철역을 삭제할 수 있다.
  - [x] 삭제 시 confirm을 이용하여 한 번 더 유저가 확인할 수 있어야 한다.
  - [x] 이미 노선에 등록된 역인 경우 삭제할 수 없다.

### 지하철 노선 관리 기능

- [x] 지하철 노선을 등록할 수 있다.
  - [x] 중복된 지하철 노선 이름이 등록될 수 없다.
  - [x] 지하철 노선의 이름은 2글자 이상, 10글자 이하여야 한다.
  - [x] 지하철 노선 생성시 필요한 값은 색상, 상행역, 하행역, (최초 상행역과 하행역 구간의)거리, 시간이다.
- [x] 지하철 노선을 수정할 수 있다.
  - [x] 지하철 노선의 이름, 상행역, 하행역, 거리, 시간, 색상을 수정할 수 있다.
- [x] 지하철 노선을 삭제할 수 있다.
- [x] 지하철 노선 리스트를 조회할 수 있다.

### 지하철 구간 관리 기능

- [x] 지하철 노선에 구간을 추가, 삭제할 수 있다.
  - 지하철 노선에 구간을 추가하는 기능은 노선에 역을 추가하는 기능이라고도 할 수 있다.
  - 역과 역사이를 구간이라 하고 이 구간들의 모음이 노선이다.
  - 하나의 역은 여러개의 노선에 추가될 수 있다.
  - 역과 역 사이에 새로운 역이 추가 될 수 있다.
  - 노선에서 갈래길은 생길 수 없다.
- [x] 구간 조회 시, 노선을 변경하면 해당 노선의 Color로 Select 엘리먼트의 배경색을 변경한다.

## 🎯🎯🎯 step3

### 전체보기 기능

- [x] 노선의 상행 종점부터 하행 종점까지 연결된 순서대로 노선과 역 목록을 조회할 수 있다.
- [x] 조회를 위한 UI는 스스로 만든다.

2021-04-07 13:51 UTC, HyeonaKwon requested changes
안녕하세요! 3단계까지 구현하시느라 고생 많으셨습니다 👍  (리뷰가 늦어 죄송합니다ㅠㅠ)

전체적인 피드백으로는
1. 각 테스트 파일의 before() 에 중복되는 코드가 있어보이는데 어떻게 해결하면 좋을지 고민해보면 좋을 것 같아요!

UI 개선점으로는
1. 모달의 x 버튼이 정상적으로 동작하지 않는데 확인 부탁드립니당! 그리고 모달 너비가 너무 좁은 것 같아요~ 모달 타이틀과 x 버튼의 높낮이도 조금 개선되었으면 좋을 것 같아요!
![image](https://user-images.githubusercontent.com/46472795/113865416-04e09a00-97e7-11eb-85a1-b4fa51b27781.png)
2. 역이나 노선을 추가할 때 제일 밑으로 추가되어서 추가되었을 때 한번에 알아차리기가 힘든 것 같아요! 맨 위로 추가하는건 어떨까요?

2021-04-07 13:51 UTC, HyeonaKwon commented on src/css/shared/modules/sizing.css
> +
bootstrap 이 떠오르네요ㅋㅋ 😭

2021-04-07 13:51 UTC, HyeonaKwon commented on src/js/components/App.js
> +      this.router[pathName]?.();
60라인이랑 여기랑 다른점은 어떤거에요? 여기는 await 가 안되어있길래요!

2021-04-07 13:51 UTC, HyeonaKwon commented on src/js/utils/customConfirm.js
> +};
이거는 왜 Promise 를 반환하는거에요~? 그냥 Promise 없이 로직 실행해도 될 것 같은데!

2021-04-07 13:51 UTC, HyeonaKwon commented on src/js/components/section/Sections.js
> +        return false;
```javascript
const section = sectionList.find((section) => station.name === section.updStation.name));

if (!section) return;

sortedSectionList.push({
  name: station.name,
  id: station.id,
  duration: section.duration,
  distance: section.distance,
});
```

2021-04-07 13:51 UTC, HyeonaKwon commented on src/js/components/section/Sections.js
> +    });
조금 복잡해보이네요! 
```javascript
const sortedSectionList = [...Array(stationList.length)].map((value, index) => {
  if (index === stationList.length - 1) return { name: stationList[index].name, id: stationList[index].id };

  const targetSection = sectionList.find((section) => stations[index].id === section.upStation.id);

  return {
    name: targetSection.upStation.name,
    id: targetSection.upStation.id,
    duration: targetSection.duration,
    distance: targetSection.distance,
  };
});
```
요정도로 줄여보는건 어떨까요?

2021-04-07 13:51 UTC, HyeonaKwon commented on src/js/components/signup/Signup.js
> +    history.pushState({ pathName: '/login' }, null, '/login');
routeTo 안에서도 똑같은 코드가 있는데 두번씩 실행하는 이유가 있나요?
그리고 components 가 history 에 push 하는것보다 router 가 관리하는게 좋을 것 같습니다!

2021-04-07 13:51 UTC, HyeonaKwon commented on src/js/components/signup/Signup.js
> +    Navigation.changeSelectedButtonColor();
네비게이션을 컨트롤하는것도 각 컴포넌트의 일은 아닌것 같습니다! 누가 해야할지 고민해보면 좋을 것 같아요!

2021-04-07 13:51 UTC, HyeonaKwon commented on src/js/components/station/Stations.js
> +        this.handleStationEditModalOpen(target);
`openStationEditModal(target)`
핸들러로 등록되는 함수가 아니라면 그냥 동사로 시작하는게 좋을 것 같아요~

2021-04-07 13:51 UTC, HyeonaKwon commented on src/js/components/station/Stations.js
> +        this.handleStationDelete(target);
바로 위 코멘트와 같은 의견입니다!

2021-04-07 13:51 UTC, HyeonaKwon commented on src/js/utils/API.js
> +};
```javascript
if (token) {
  option.headers.Authorization = `Bearer ${token}`;
}
```
```javascript
const option = {
  headers: { ... },
  body: ...,
};
```
는 여전히 중복이 되어요! 중복을 줄일 수 있도록 고민해보면 좋겠네요!

2021-04-08 07:18 UTC, yungo1846 commented on src/css/shared/modules/sizing.css
> +
하핳 그런가요? 😂

2021-04-08 07:33 UTC, yungo1846 commented on src/js/components/App.js
> +      this.router[pathName]?.();
앗 그러네요 😂
이전에 로그인 상태에서 네비게이션 버튼을 눌렀을 때, 네비게이션 버튼 색상이 뒤늦게 바뀌는 문제가 있어서 동기처리를 했습니다. 하지만 리팩토링에서 해당 이슈를 수정하여 60번 라인의 await을 삭제해도 됐는데 미처 삭제하지 못했습니다. 감사합니다 👍

2021-04-08 07:38 UTC, yungo1846 commented on src/js/utils/customConfirm.js
> +};
컨펌 창이기 때문에 컨펌창의  확인 버튼이 눌리기 전까지 함수의 실행을 멈추기 위해 promise를 반환하도록 하였습니다! 콜백함수로도 구현할 수 있지만 Promise를 쓰는게 개인적으로 가독성이 더 좋았습니다 😄

``` javascript
async deleteLine(target) {
    const $lineListItem = target.closest('.line-list-item');
    const lineName = $lineListItem.querySelector('.line-name').innerText;
    const lineId = target.dataset.id;

    const confirm = await customConfirm(MESSAGE.DELETE_CONFIRM(lineName));
    // Promise로 컨펌창의 버튼 클릭여부를 기다립니다.
    // 만약 동기적으로 기다리지 않는다면 컨펌창의 '확인', '취소' 클릭여부와 관계없이 해당 노선을 삭제해버리는 문제가 생깁니다.

    if (!confirm) {
      return;
    }

    const isDeleted = await serviceAPI.deleteLine({
      token: this.#token,
      id: lineId,
    });

    if (!isDeleted) {
      showSnackbar(SNACKBAR_MESSAGE.DELETE_FAILURE);
      return;
    }

    $lineListItem.remove();
    showSnackbar(SNACKBAR_MESSAGE.DELETE_SUCCESS);
  }

  handleLineModalClose({ currentTarget, target }) {
    if (currentTarget === target || target === this.$modalCloseButton) {
      this.$modal.classList.remove('open');
    }
  }
```

2021-04-08 07:39 UTC, yungo1846 commented on src/js/components/section/Sections.js
> +    });
오 훨씬 깔끔해진 것 같습니다!
코드에 바로 적용하였습니다 👍👍

2021-04-08 07:40 UTC, yungo1846 commented on src/js/components/signup/Signup.js
> +    history.pushState({ pathName: '/login' }, null, '/login');
history.pushstate를 없애기 위해 routeTo를 만들었는데 리팩토링 과정에서 미처 삭제하지 않은 부분이 있었네요 ㅎ... 다음부터는 리팩토링을 좀 더 꼼꼼하게 놓치는 부분없이 하도록 하겠습니다 🙏

2021-04-08 07:43 UTC, yungo1846 commented on src/js/components/signup/Signup.js
> +    Navigation.changeSelectedButtonColor();
말씀해주신대로 각 컴포넌트가 네비게이션을 컨트롤하는 것은 옳지 않은 방향이라고 생각합니다. 특히나 기존에는 `changeSelectedButtonColor()`를 Navigation의 정적 메소드로 만들어 사용했습니다. `changeSelectedButtonColor()`를 정적 메소드가 아닌 일반 메소드로 바꾸고 다른 컴포넌트에서 네비게이션에 관여하지 않도록 수정하였습니다 👍👍👍

2021-04-08 07:45 UTC, goni-ssi commented on src/js/components/station/Stations.js
> +        this.handleStationEditModalOpen(target);
당연하게 이벤트와 연관이 있는 함수니까 관성적으로 `handle-` prefix를 썼습니다. 하지만 짚어주신대로 익명함수 안에서 분기로 처리되는 함수는 이벤트 핸들러로 등록되는 함수가 아니므로 일반 동사로 시작하는게 더 좋을 것 같습니다! 감사합니다 ㅎㅎ

2021-04-08 07:45 UTC, yungo1846 commented on src/js/components/station/Stations.js
> +        this.handleStationDelete(target);
위와 같이 수정하였습니다!

2021-04-08 07:47 UTC, yungo1846 commented on src/js/utils/API.js
> +};
중복되는 부분을 getOption이라는 함수로 따로 관리하도록 했습니다. 😄
``` javascript
const getOption = ({ method, contents, token }) => {
  const option = {
    method: method,
    headers: {
      'Content-Type': 'application/json',
    },
  };

  if (contents) {
    option.body = JSON.stringify(contents);
  }

  if (token) {
    option.headers.Authorization = `Bearer ${token}`;
  }

  return option;
};
```

2021-04-08 07:49 UTC, yungo1846 commented
리뷰 남겨주셔서 감사합니다.
방학 전까지 PR을 보내야한다는 생각에 디테일한 부분에서 미흡했던 점이 있던 것 같습니다... 😂
그래도 리뷰어님께서 꼼꼼하게 봐주신 덕에 이전보다 완성도를 높일 수 있었습니다. 감사합니다 👍👍👍

2021-04-12 13:28 UTC, HyeonaKwon commented on src/js/utils/customConfirm.js
> +};
음 customConfirm 에서 반환하는 Promise 는 html dom element 생성하고 event listener 를 등록하는 일만 하고있는거로 보이는데, 제가 이해를 잘못한건가요??

2021-04-12 13:32 UTC, HyeonaKwon commented
https://github.com/woowacourse/javascript-subway/pull/61#discussion_r611628500
요거 코멘트만 한번 더 확인 부탁드려요!

2021-04-14 00:39 UTC, yungo1846 commented on src/js/utils/customConfirm.js
> +};
말씀해주신대로 리턴되는 프로미스는 DOM element를 생성하고 event Listener 등록하는 일을 하고 있습니다. 😀
그럼에도 굳이 프로미스를 반화하는 이유는 최대한 기존 `window.confirm`과 비슷하게 코드를 작성하기 위함이였습니다. `window.confirm`은 사용자가 확인 혹은 취소 버튼을 클릭하기 전까지 함수의 실행을 멈춥니다. customConfirm도 사용자가 확인 혹은 취소 버튼을 클릭하기 전까지 최소한 customConfirm을 실행한 함수 내에서는 동기적으로 실행되도록 하기위해 Promise를 반환하도록 하였습니다..! 혹시 더 개선하거나 변경되야할 점이 있을까요? 😂

2021-04-14 00:42 UTC, yungo1846 commented
[#61 (comment)](https://github.com/woowacourse/javascript-subway/pull/61#discussion_r612861339)
코멘트 확인해주시면 감사하겠습니다 🙆‍♂️

2021-04-14 09:14 UTC, HyeonaKwon commented on src/js/utils/customConfirm.js
> +};
아!!!!!!! resolve() 를 click 이벤트 핸들러 안에서 하고 있는걸 지금 봤네요ㅠㅠ 말씀해주신 내용 맞습니당!

2021-04-14 09:15 UTC, HyeonaKwon approved these changes
크 수정사항 모두 확인했습니다! 제 덕분에 완성도가 높아졌다니.. 말씀만으로도 감사해요 :)
이제 방학 푹 쉬세요!! 👍  고생하셨습니다.

2021-04-14 09:15 UTC, merged

2021-04-19 14:22 UTC, yungo1846 commented
## 레벨 1-4. 지하철 노선도 학습로그
### [📌 학습 로그](https://yung-developer.tistory.com/90)