[2, 3단계 - 지하철 노선도 미션] 브랜(서지환) (본문 작성중입니다.)
woowacourse/javascript-subway pull request #66
Opened 2021-04-03 16:58 UTC by seojihwan

2021-04-07 15:53 UTC, wow9144 requested changes
어려운 미션 진행 하시느라 수고 많으셨습니다.
코드 곳곳에서 고민의 흔적이 많이 느껴졌습니다.

코드의 퀄리티를 지금 보다 훨씬 올릴 주요 키워드로 
1. 중복
2. 책임
을 드리고 싶습니다.

전반적으로 중복이 많은데 이 부분만 줄여도 코드가 많이 줄어들 것 같습니다.
특히 컴포넌트에서 api를 찌르고 catch 하는 부분들은 세부 코멘트에도 적어드렸지만, 컴포넌트에서 그 일을 하게 되면 모든 컴포넌트에 똑같은 코드가 계속 들어가도록 코드가 전개됩니다. 
어떻게 해결 하면 될지 이 부분을 중점적으로 고민해보시면 좋을 것 같습니다.

하나의 메서드가 너무 많은 일을 하고 있습니다.
너무 많은 일을 한다는 것은 다시 말하면 너무 많은것을 알고 있다고 표현 할 수 있는데 이 역시 세부 코멘트 참고하시어 적절하게 책임을 분산시켜주시면 좋을 것 같습니다.

2021-04-07 15:53 UTC, wow9144 commented on src/js/App.js
> +  setIsLogin(isLogin) {
setLoginState, setLoginStatus 같은 네이밍이 더 적절할 것 같습니다.

2021-04-07 15:53 UTC, wow9144 commented on src/js/App.js
> +  addStaticEventListeners() {
이름에 Static이 들어간 의도가 코드에서는 잘 드러나지 않는것 같은데 어떤 이유이실까요?

2021-04-07 15:53 UTC, wow9144 commented on src/js/Pages/Line/AddModal/index.js
> +        await privateApis.lines.post({
이렇게 컴포넌트에서 api 를 직접 찌를 경우 컴포넌트가 지금처럼 너무 많은것을 알아야 하는 경우가 생깁니다.
모달은 그저 모달에서 수집할 수 있는 정보들(e.target[].value..)만 알고 있는게 좋고, 그 외의 정보는 모달이 모르도록 하는게 좋습니다. 
token 이 로컬스토리지에 저장되는지 쿠키에 저장되는지 브라우저 DB에 저장되는지 그런것들은 모달의 관심사가 아니기 때문에 이런것은 컴포넌트와 api 사이의 다른 레이어가 알고 처리하도록 하는게 좋습니다.
token 이 expired 되었는지 여부도 역시 컴포넌트의 관심사가 아니기 때문에, 컴포넌트의 catch 구문에서ExpiredTokenError를 검사하는 코드가 존재하도록 한다면 필시 이 try catch 코드는 모든 컴포넌트에 전방위적으로 중복되게 됩니다.

2021-04-07 15:53 UTC, wow9144 commented on src/js/Pages/Line/AddModal/index.js
> +class AddModal extends ModalComponent {
AddModal 네이밍의 추상화 정도를 낮추고 좀 더 구체화하는것이 의도를 드러내기에 더 좋을 것 같습니다.
privateApis.lines.post() 가 아닌, 다른 post 하는 모달도 있을 수 있는데 AddModal 은 마치 post 하는 모든 모달을 구현 할 때 상속해야 하는 클래스처럼 느껴집니다.

2021-04-07 15:53 UTC, wow9144 commented on src/js/Pages/Line/EditModal/index.js
> +  fillTargetInForm() {
AddModal 과 정확히 중복이네요.
왜 중복이 생겼을지 고민해보시고, 어떻게 하면 중복을 없앨 수 있을지도 고민해보시면 좋을 것 같습니다.
이 메서드 뿐만 아니라 EditModal 자체가 AddModal 과 중복이라고 볼 수 있습니다.

2021-04-07 15:53 UTC, wow9144 commented on src/js/Pages/Map/index.js
> +class Map extends Component {
자바스크립트의 내장된 Map Api 가 있기 때문에 Map은 사용 할 수 없는 키워드라고 생각하시는게 좋습니다.
class Map 을 선언하시게 되면 기존의 내장 Map을 덮어쓰게 되고 그럼 이 클래스가 로드된 순간 내장 Map을 사용하고 있던 기존의 다른 라이브러리나 코드들이 다 에러를 뿜고 망가지게 됩니다. :)

2021-04-07 15:53 UTC, wow9144 commented on src/js/Pages/Section/AddModal/index.js
> +class AddModal extends ModalComponent {
위 코멘트에서 AddModal 의 추상화 정도가 좀 높다고 말씀드렸었는데 Line/AddModal, Section/AddModal 로 구분이 되어 있는것이었군요.
이 부분은 사람마다 취향이 좀 갈리는데, Line/LineAddModal 로 하면 Line 이 의미를 중복으로 전달하고 있기 때문에 제거되어야 한다고 볼 수 있긴 합니다.
반면에 중복된 의미를 제거하면 에터터(IDE)에서 AddModal 로 검색하면 수 많은 AddModal 이 나오기 때문에 찾아야 하는 불편함이 있기도 합니다.
장단이 있으니 이 부분은 편하신대로 하시다가 바꿔야 할 이유가 느껴지시면 그 때 다시 생각해보셔도 될 것 같긴 합니다.

2021-04-07 15:53 UTC, wow9144 commented on src/js/Router.js
> +class Router {
Router라는 이름의 추상화 정도는 gePage, isLogin, setIsLogin등 그 외에 new 로 생성하고 있는 모든 컴포넌트들 같은 구체적인것들을 몰라야 합니다.
Router는 그저 라우팅을 하는 역할로만 존재해야 합니다.
라우팅이 필요한 새로운 페이지가 추가되더라도 이 Router 클래스 생성자의 pageComponents 를 수정하는 것이 아니라 모든 구체적인것들은 이 Router를 생성하여 사용하는 쪽에서 주입하도록 해야 하는것입니다.
그리하면 Router는 라우팅만 하는 역할로 남고, 지하철 노선도 미션이 아닌 다른 프로젝트에서도 라우팅이 필요하면 가져가 쓸 수 있도록 말입니다.

지금 단계에서는 이렇게 재사용 가능하도록 코드를 작성하는게 어려우실 수 있으나(어려운게 당연합니다.) 시도 해보시는 것만으로도 많은 것을 얻으실 수 있으실거라고 생각됩니다. 


* 그 정도로 추상화 할 의도가 애초부터 없었고 그냥 여기서만 한 번 쓰이고 마는 구체적인 클래스라면 그냥 이대로 두셔도 상관 없을 것 같습니다.

2021-04-18 11:06 UTC, seojihwan commented on src/js/App.js
> +  addStaticEventListeners() {
각 컴포넌트들의 이벤트리스너들은 렌더링 될 때 같이 등록될 수 있도록 설정하였는데
위의 메서드는 1번추가된 후 사라지지 않도록 설정하였습니다.
static 메서드와 관련이 없고, 단지 정적이라는 사전적의미로 네이밍을 정하였습니다.
네이밍이 혼동을 줄 수 있는 것 같지만 설계 자체가 깔끔하지 않아 어색한 네이밍이 들어간 것 같습니다.

2021-04-18 11:16 UTC, seojihwan commented on src/js/Pages/Line/AddModal/index.js
> +        await privateApis.lines.post({
```js
class HTTPError extends Error {
  constructor(status, message) {
    super(message);

    this.status = status;
  }

  handleError() {
    switch (this.status) {
      case 401:
        App.setLoginStatus(false);
        Router.goPage(UNAUTHENTICATED_LINK.LOGIN);

      default:
        showSnackbar(this.message);
        break;
    }
  }
}
```

에러 객체에서 에러 핸들링에 관한 로직을 추가하고 instance를 검사하여 에러를 처리하도록 수정하였습니다.

또한 토큰등의 정보는 api를 호출할 때 확인하여 처리할 수 있도록 분리하였습니다.

```js
try {
      await Apis.stations.delete({
        stationId,
        accessToken,
      });

      await this.updateSubwayState();
    } catch (error) {
      if (error instanceof HTTPError) {
        error.handleError();
      }

      console.error(error.message);
    }
```

2021-04-18 11:19 UTC, seojihwan commented on src/js/Pages/Map/index.js
> +class Map extends Component {
사용안하기 때문에 Map의 네이밍을 사용하였는데 엄청 위험한 행동을 하고있었네요 😂

2021-04-18 11:21 UTC, seojihwan commented on src/js/Router.js
> +class Router {
Router의 유연성을 높여주기 위해서 App에서 각 페이지 컴포넌트를 주입하는 방식을 사용하였습니다.

2021-04-18 11:29 UTC, seojihwan commented on src/js/Pages/Line/AddModal/index.js
> +        await privateApis.lines.post({
Api에서 토큰이 만료된 것을 감지하였을 때 Navitaion을 변화 시켜 로그인과 회원가입의 메뉴만 화면에 보이도록 설정해야합니다.

중앙 스토어를 따로 두지 않아 App의 상태를 직접변경해야 하는데 Api가 App을 알고 있어야하는 점이 어색했습니다.
기능을 구현하기 위해 App클래스 생성자를 export하는 방식에서 App 인스턴스를 생성하고 export하는 방식을 사용하였습니다.

```js
const initalState = {
  loginStatus: false,
  stations: [],
  lines: [],
};

const app = new App({
  parentNode: $('#app'),
  state: initalState,
  Router,
});

export default app;
```

2021-04-18 14:02 UTC, seojihwan commented on src/js/App.js
> +  setIsLogin(isLogin) {
네이밍이 모호했네요~ setLoginStatus로 변경하였습니다

2021-04-18 14:10 UTC, seojihwan commented on src/js/Pages/Line/EditModal/index.js
> +  fillTargetInForm() {
모달을 분리하여 중복을 허용할 것인지 하나의 모달을 사용할지 고민을 하였습니다.

초기에는 라인 추가버튼, 선택버튼을 누를 때 마다 모달의 템플릿을 변경하여 다른 로직을 수행하게 변경하는 과정을 거쳤습니다. 하지만 개인적으로 이러한 로직이 깔끔하지 않다고 생각하였습니다.
차나리 중복을 어느정도 허용하고 코드를 이해하기 쉽도록 구성해보았는데 모달이 2개 떠있고, 중복이 생각보다 많다는 점에서 많은 고민이 들어 어려웠습니다😂

2021-04-20 16:50 UTC, wow9144 commented on src/js/Pages/Line/EditModal/index.js
> +  fillTargetInForm() {
중복을 허용한다면 어느정도 허용할 것 인가의 그 `어느정도`라는 것이 팀원이 혼자가 아닌 2명 이상만 되어도 정확히 일치시키는게 매우 어렵습니다. (꼭 중복 뿐만 아니라 `어느정도` 라는 말이 붙을 수 있는 모든 것이 똑같습니다😂)
그래서 누군가에게는 중복으로 보여서 고쳐야 할 코드로 보이고 누군가에게는 문제가 없는것으로 보이고...해서 지리한 논쟁을 하기도 합니다.
중복을 제거하는것도 어렵지만 발견하는것(누군가에겐 중복으로 보이고 누군가에겐 안보이고)은 더 어려우니 시간이 차차 해결해줄 것 입니다. 지금 정도의 고민을 해보신 것 만으로도 충분합니다!

2021-04-20 16:53 UTC, merged

2021-04-20 16:53 UTC, wow9144 commented
수고 많으셨습니다.
다음 로또 미션도 기대 하겠습니다!
(이미 제출되어 있지만 그것은 내일 피드백 드리겠습니다! 조금 늦어져서 죄송합니다!)

2021-04-26 23:47 UTC, seojihwan commented
# 학습로그
## 지속, 성장 가능한 소프트웨어
- [지속, 성장 가능한 소프트웨어](https://www.notion.so/b446359abcdd447e83ae798a71779db9)

## 태그
- Business Logic,  Layer, Module

2021-05-02 12:55 UTC, wow9144 commented on src/js/Pages/Line/AddModal/index.js
> +        await privateApis.lines.post({
여기 질문이 있는데 제가 못보고 지나쳤나봅니다. 
피드백을 위해 예전 미션을 보다가 발견해서, 보실지 모르겠지만 뒤늦게 답변드립니다. 
Api 함수는 말씀하신것처럼 App을 알지 못합니다.
그래서 이런 토큰 만료를 처리를 위해 미들웨어를 두고 여기서 처리하도록 하여 api함수를 호출하는쪽도 토큰에 대해 신경쓰지 않고, api 함수도 토큰을 신경 쓰지 않는 형태로 구현합니다.
이 부분은 아마 앞으로 미션을 해결해나가시면서 자연스럽게 알게 되실 부분이 될 것 같습니다.