[2,3단계 - 지하철 노선도 미션] 심바(임선빈) 미션 제출합니다.
woowacourse/javascript-subway pull request #73
Opened 2021-04-23 04:32 UTC by 0imbean0

안녕하세요.
우아한테크코스 3기 심바입니다.

2, 3단계 미션 제출합니다.

이번 단계에서는 추상 클래스(component, stateManager)를 여러 번 수정하면서 어떻게 더 잘 추상화 시킬 수 있을지 고민하였습니다. 

### 데모 사이트 - [지하철 노선도](https://simba-subway.netlify.app/) 
##### (데모 아이디 - simba@test.com, 비밀번호 - test1234)

## 역 관리
![1](https://media.giphy.com/media/LAP5vjZTgIuh4tqZXe/giphy.gif) 

## 노선 관리
![2](https://media.giphy.com/media/PESlRP3GFzYYMPOr1p/giphy.gif) 

## 구간 관리
![3](https://media.giphy.com/media/5POl8NxiHrNOBkOjSn/giphy.gif) 

## 전체 보기
![4](https://media.giphy.com/media/00YR1XvdvYEUjweCfK/giphy.gif)

2021-04-23 16:16 UTC, ysm0622 requested changes
3단계까지 고생하셨습니다! 👏 👏 👏 👏 👏 👏

2021-04-23 16:16 UTC, ysm0622 commented on src/js/components/line/index.js
> +    });
매번 accessToken을 파라미터로 넘기는것보다 fetch 하기 직전에 직접 fetch를 호출하는 함수에서 accessToken을 꺼내쓰면 어떨까요? 매번 함수의 파라미터로 accessToken을 넘기지 않아도 되지 않을까요? 👀

2021-04-23 16:16 UTC, ysm0622 commented on src/js/components/map/template/main.js
> +          return `<option value="${line.id}">${line.name}</option>`;
return문을 생략하면 좋을것같아요 👍

2021-04-23 16:16 UTC, ysm0622 commented on src/js/components/map/template/main.js
> +};
어떤 template은 함수이름에 template이 포함되고, 어떤 함수는 그렇지 않은데, 어떤 기준인가요? 👀

2021-04-23 16:16 UTC, ysm0622 commented on src/js/components/map/template/main.js
> +};
이정도 크기의 템플릿을 분리한 이유는 무엇인가요? 👀

2021-04-23 16:16 UTC, ysm0622 commented on src/js/components/section/template/modal.js
> +            </select>
여기도 모두 return을 생략할 수 있을것같아요 👍

2021-04-23 16:16 UTC, ysm0622 commented on src/js/core/ModalComponent.js
> +  fillTargetInForm() {}
이 body가 없는 함수는 왜있는건가요? 👀

2021-04-27 00:56 UTC, 0imbean0 commented
# 학습 로그

## Form

- 여러 개의 input의 값를 가져오기 위해 각  input을 querySelector로 찾아서 value 가져왔는데 name 속성을 이용하면 한번에 가져올 수 있었다.
- Form 내부의 버튼은 기본 타입이 submit이다. 이때 버튼은 클릭과 enter에 모두 submit 이벤트를 발생시킨다.
- 링크
  - https://developer.mozilla.org/ko/docs/Web/HTML/Element/form
  - https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

### currentTarget

- 이벤트 위임을 할 때 event target과 currentTarget을 비교하면 이벤트 대상을 쉽게 찾을 수 있다.
-  event target은 이벤트를 발생시킨 요소, currentTarget은 이벤트가 걸려있는 요소
- 링크
  - https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

2021-05-26 08:36 UTC, merged